module.exports = {
  data: [
    {
      id: 1,
      name: "郑州市纪委监委启动对赋红码问题调查问责程序111111111",
      age: "20",
      gender: "男",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "架构师",
    },
    {
      id: 2,
      name: "众多来唐旅客滞留唐山火车站,工作人员:必须提前48小时报备",
      age: "20",
      gender: "男",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "算法工程师",
    },
    {
      id: 3,
      name: "河南省疫情防控指挥部重申：健康码仅用于疫情防控",
      age: "45",
      gender: "女",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "AI工程师",
    },
    {
      id: 4,
      name: '合伙公司偷逃税被罚 贾乃亮自称"投资黑洞":远离投资',
      age: "21",
      gender: "女",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "微前端",
    },
    {
      id: 5,
      name: "肃兰州中考物理泄题？当地教育局：未发生试题泄露",
      age: "20",
      gender: "女",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "JAVA研发",
    },
    {
      id: 6,
      name: "江西上饶一女子遭多人殴打倒地后被猛踹？警方：正处理",
      age: "35",
      gender: "男",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "产品经理",
    },
    {
      id: 7,
      name: "贵州生态日｜沿河：65万尾鱼苗“落户”乌江流域",
      age: "54",
      gender: "男",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "UI",
    },
    {
      id: 8,
      name: "目击者讲述兰州化工企业爆炸：3米长工字钢被炸出200多米",
      age: "20",
      gender: "男",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "架构师",
    },
    {
      id: 9,
      name: "网传江西上饶多名男子围殴一女子 警方:已抓获14名涉案人员",
      age: "20",
      gender: "男",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "算法工程师",
    },
    {
      id: 10,
      name: "走进县城看发展｜贵州龙里：山里山外 都是一片新天地",
      age: "45",
      gender: "女",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "AI工程师",
    },
    {
      id: 11,
      name: "chatGPT带动人工智能市场",
      age: "45",
      gender: "女",
      phone: "",
      email: "",
      create_date: "2023-01-07 08:12:39",
      profession: "AI工程师",
    },
  ],
  total: 11,
};
